services:
  - type: web
    name: sawt-aljazair-api
    runtime: node
    rootDir: backend
    buildCommand: npm install --no-audit --no-fund && npx prisma generate
    startCommand: npm run start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: PUBLIC_BASE_URL
        value: https://cstatwt-aljtaztair.onrender.com
      - key: S3_PUBLIC_BASE_URL
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_REGION
        value: auto
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
